source 'https://cdn.cocoapods.org/'

use_frameworks!
use_modular_headers!
platform :ios, '10.0'
inhibit_all_warnings!
install! 'cocoapods', :deterministic_uuids => false
target 'ShFlyKit_Example' do
  pod 'ShFlyKit', :path => '../'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
end
